# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c657e3d4f0f734c690f58c7623601c6739de82addc2fb9da7f6771ba38d4c88d02fbe8ed1aab454e122c12e1b1962b081c6344a9b7a55a455ce4835def5ae5da

test:
  secret_key_base: 3d479caf9a7ce4c379e068dd2600f09805421d1390215e923d41473fdbce9ecf7dd3a496817742a4d3d98f48132b91f48e0e4f528971594cc725db4f2cb1459d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
